### ISSUE TITLE
Update notification box for latest round of updates

### ISSUE THREAD

**Issue by aazaff** [azgs/azlibrary_react#25]
Similar to what we did in #22, we'll want to showcase our recent improvements. I think violet might be a nice color this time...

1. Show total number of collections.
2. Sort by year
3. New versioning options (maybe don't list this since it is kind of backend issue)
4. What else?

**Comment by NoisyFlowers** [comment]
I think we should mention the versioning changes, since it has effected the collection display page.

Something like:
3. Multiple lineage versioning (collection can supersede/be superseded by one or more collections.

Feels like there should be something else, but I can't think of anything that is relevant to the react client.

**Comment by NoisyFlowers** [comment]
In 26ffefd1eaeadc555ec0a4b9f5bf6a0e2713525c

ddm-dev branch, running on dev

**Comment by NoisyFlowers** [comment]
Further modified in 5862869521f2c0e69e65e6d261c96acc4e23ab09
